# Generated by Django 4.2.3 on 2023-08-06 11:25

import chat.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_type', models.CharField(choices=[('direct', 'Direct'), ('group', 'Group')], default='direct', max_length=7)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('topic', models.CharField(blank=True, max_length=100, null=True)),
                ('last_message_read_time', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('audio', 'Audio'), ('image', 'Image'), ('video', 'Video')], default='text', max_length=10)),
                ('text_content', models.TextField(blank=True, help_text='Text content for text messages', max_length=500, null=True)),
                ('audio_file', models.FileField(blank=True, help_text='Audio content for audio messages', null=True, upload_to='audio_messages/', validators=[chat.validators.validate_audio_file_extension])),
                ('image_file', models.ImageField(blank=True, help_text='Image content for image messages', null=True, upload_to='image_messages/')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read')], default='sent', max_length=10)),
                ('read', models.BooleanField(default=False)),
                ('flagged', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.chatroom')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.message')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
