# Generated by Django 4.2.3 on 2023-08-09 13:25

import chat.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='document_file',
            field=models.FileField(blank=True, help_text='Document content for document messages', null=True, upload_to='document_messages/', validators=[chat.validators.validate_document_file_extension]),
        ),
        migrations.AddField(
            model_name='message',
            name='video_file',
            field=models.FileField(blank=True, help_text='Video content for video messages', null=True, upload_to='video_messages/', validators=[chat.validators.validate_video_file_extension]),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('audio', 'Audio'), ('image', 'Image'), ('video', 'Video'), ('document', 'Document')], default='text', max_length=10),
        ),
    ]
