name: Flutter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.x'

      - name: Install dependencies
        working-directory: ./frontend/mobile-app/unbowed_flutter
        run: flutter pub get

      - name: Run tests
        working-directory: ./frontend/mobile-app/unbowed_flutter
        run: flutter test
