name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Install dependencies
        working-directory: ./frontend/mobile-app/unbowed_flutter
        run: dart pub get

      - name: Analyze project source
        working-directory: ./frontend/mobile-app/unbowed_flutter
        run: dart analyze

      - name: Run tests
        working-directory: ./frontend/mobile-app/unbowed_flutter
        run: dart test
